import { ProjectIdea } from '../App';
import { Leverage } from '../components/LeverageCard';

export function getMockLeverages(): Leverage[] {
  return [
    {
      id: '1',
      leverage: 'Product Launch',
      strategicImpact: 'Use Case Creation',
      description: 'Figma just launched Figma Make, a competition to Lovable. They are actively looking for early adopter user adoption, real-world use cases, and community-generated examples to showcase the platform\'s capabilities and build momentum.',
      company: 'Figma',
      relevance: 'high',
    },
    {
      id: '2',
      leverage: 'Thought Leadership',
      strategicImpact: 'Community Engagement',
      description: 'Paul Copplestone (Supabase CEO) has been actively tweeting about AI-powered database tools and the future of backend development. Projects that demonstrate innovative AI + Supabase integrations could catch his attention and potentially get featured in their showcase.',
      company: 'Supabase',
      relevance: 'high',
    },
    {
      id: '3',
      leverage: 'Technology Release',
      strategicImpact: 'Integration Play',
      description: 'Algolia recently released AI Search capabilities, combining semantic search with their traditional keyword search. They\'re seeking projects that demonstrate unique applications of this new feature, especially when integrated with modern backend platforms.',
      company: 'Algolia',
      relevance: 'medium',
    },
    {
      id: '4',
      leverage: 'Market Positioning',
      strategicImpact: 'Evangelization / Awareness',
      description: 'Figma is positioning itself as the design-to-development bridge. Projects that seamlessly connect design workflows to live code or deployments showcase their platform\'s potential and help validate their market positioning.',
      company: 'Figma',
      relevance: 'high',
    },
    {
      id: '5',
      leverage: 'Developer Experience',
      strategicImpact: 'Use Case Creation',
      description: 'Supabase is heavily investing in developer experience and wants to show how quickly developers can build production-ready applications. Projects that go from zero to deployed in the hackathon timeframe are perfect proof points.',
      company: 'Supabase',
      relevance: 'medium',
    },
    {
      id: '6',
      leverage: 'Enterprise Adoption',
      strategicImpact: 'Use Case Creation',
      description: 'Algolia is expanding into enterprise markets and needs compelling case studies. Projects that solve enterprise-level search challenges or demonstrate scalability and performance could become marketing assets.',
      company: 'Algolia',
      relevance: 'medium',
    },
  ];
}

export function getMockProjects(sponsors: string[]): ProjectIdea[] {
  const baseProjects: ProjectIdea[] = [
    {
      id: '1',
      title: 'Real-time Collaborative Design Feedback Tool',
      description: 'A platform that combines Figma designs with real-time commenting and annotation powered by Supabase realtime subscriptions and Algolia search.',
      score: 95,
      category: 'Collaboration Tools',
      difficulty: 'intermediate',
      techRequirements: 'moderate',
      sponsors: ['Supabase', 'Figma', 'Algolia'],
      why: 'This project leverages ALL three sponsors, demonstrating deep technical integration. The judges are CEOs who value products that showcase their platforms working together seamlessly. Real-time collaboration is a hot topic and directly appeals to all three company missions.',
      leverages: [
        'Supabase Realtime for instant comment synchronization across users',
        'Figma API for embedding and manipulating designs directly in the app',
        'Algolia for lightning-fast search across designs, comments, and feedback history',
        'Demonstrates understanding of each platform\'s core strengths',
      ],
      requiredSkills: [
        'React/Next.js frontend development',
        'Supabase authentication & realtime',
        'Figma Plugin or API integration',
        'Algolia InstantSearch implementation',
      ],
      estimatedTime: '24-36 hours',
    },
    {
      id: '2',
      title: 'Design System Component Library Generator',
      description: 'Automatically generate searchable, documented component libraries from Figma designs with usage analytics stored in Supabase.',
      score: 92,
      category: 'Developer Tools',
      difficulty: 'advanced',
      techRequirements: 'highly-technical',
      sponsors: ['Figma', 'Supabase', 'Algolia'],
      why: 'Addresses a real pain point for designers and developers. Shows technical sophistication while solving a practical problem. The analytics component adds business intelligence that judges will appreciate.',
      leverages: [
        'Figma API for extracting component definitions and styles',
        'Supabase for storing usage metrics and component metadata',
        'Algolia for searchable documentation with typo-tolerance',
        'Demonstrates practical value for enterprise customers',
      ],
      requiredSkills: [
        'Deep understanding of design systems',
        'Figma API & Plugin development',
        'Database schema design',
        'Full-stack development',
      ],
      estimatedTime: '30-48 hours',
    },
    {
      id: '3',
      title: 'Hackathon Project Idea Generator (Meta!)',
      description: 'An AI-powered tool that analyzes hackathon details and suggests winning project ideas with searchable database of past winners.',
      score: 88,
      category: 'AI & Innovation',
      difficulty: 'beginner',
      techRequirements: 'low-code',
      sponsors: ['Supabase', 'Algolia'],
      why: 'Meta approach shows creativity and self-awareness. Low technical barriers mean more time for polish and presentation. The AI angle is trendy and the practical application is immediately clear.',
      leverages: [
        'Supabase Edge Functions for AI prompts (or external AI API)',
        'Supabase database for storing hackathon data and project templates',
        'Algolia for fast searching through historical hackathon winners',
        'Simple to explain, impressive results',
      ],
      requiredSkills: [
        'Basic frontend (React)',
        'API integration (OpenAI/Claude)',
        'Simple database operations',
        'Good UX/UI design sense',
      ],
      estimatedTime: '16-24 hours',
    },
    {
      id: '4',
      title: 'Visual Database Builder with Figma Integration',
      description: 'Design your database schema visually in Figma, then auto-generate Supabase tables and relationships with searchable documentation.',
      score: 90,
      category: 'Developer Tools',
      difficulty: 'advanced',
      techRequirements: 'highly-technical',
      sponsors: ['Figma', 'Supabase', 'Algolia'],
      why: 'Bridges the gap between design and development workflows. Shows deep technical knowledge of both platforms. The visual-to-code transformation is impressive and practical for non-technical stakeholders.',
      leverages: [
        'Figma Plugin API for creating custom database design interfaces',
        'Supabase Management API for programmatic table creation',
        'Algolia for searchable schema documentation and examples',
        'Solves a real problem in the development workflow',
      ],
      requiredSkills: [
        'Figma Plugin development',
        'Database architecture knowledge',
        'Supabase API expertise',
        'Code generation techniques',
      ],
      estimatedTime: '36-48 hours',
    },
    {
      id: '5',
      title: 'Design Asset Library with Smart Search',
      description: 'Centralized repository for design assets from Figma with AI-powered tagging and lightning-fast search powered by Algolia.',
      score: 85,
      category: 'Design Tools',
      difficulty: 'intermediate',
      techRequirements: 'moderate',
      sponsors: ['Figma', 'Algolia', 'Supabase'],
      why: 'Practical tool that design teams actually need. The AI tagging adds innovation while the search functionality showcases Algolia perfectly. Easy to demo with visual results.',
      leverages: [
        'Figma API for asset extraction and management',
        'Algolia for instant search with faceting and filtering',
        'Supabase for user management and asset metadata storage',
        'AI APIs for automated asset categorization',
      ],
      requiredSkills: [
        'Frontend development',
        'Figma API basics',
        'Algolia search implementation',
        'Optional: AI/ML for tagging',
      ],
      estimatedTime: '20-30 hours',
    },
    {
      id: '6',
      title: 'User Research Insights Dashboard',
      description: 'Collect, analyze, and search user feedback with Figma prototype integration and real-time collaboration features.',
      score: 87,
      category: 'Product Management',
      difficulty: 'intermediate',
      techRequirements: 'moderate',
      sponsors: ['Supabase', 'Algolia', 'Figma'],
      why: 'Appeals to product managers and researchers, showing you understand the full product development cycle. The real-time aspect is impressive and the search functionality is essential for the use case.',
      leverages: [
        'Supabase for storing feedback and user data with realtime updates',
        'Algolia for searching across all feedback with advanced filtering',
        'Figma embeds for linking feedback to specific design screens',
        'Addresses a workflow pain point many teams experience',
      ],
      requiredSkills: [
        'Full-stack web development',
        'Data visualization',
        'Supabase realtime features',
        'Search implementation',
      ],
      estimatedTime: '24-36 hours',
    },
    {
      id: '7',
      title: 'No-Code Website Builder with Figma Import',
      description: 'Turn Figma designs into live websites with a drag-and-drop editor, backed by Supabase CMS and Algolia site search.',
      score: 93,
      category: 'No-Code Tools',
      difficulty: 'advanced',
      techRequirements: 'highly-technical',
      sponsors: ['Figma', 'Supabase', 'Algolia'],
      why: 'Highly ambitious project that could genuinely disrupt the market. Shows technical excellence across multiple domains. The no-code angle makes the value proposition immediately clear to non-technical judges.',
      leverages: [
        'Figma API for design import and conversion to HTML/CSS',
        'Supabase as headless CMS backend with authentication',
        'Algolia for implementing site-wide search functionality',
        'Demonstrates full product thinking beyond just technical execution',
      ],
      requiredSkills: [
        'Advanced frontend engineering',
        'Design-to-code conversion logic',
        'CMS architecture',
        'Complex state management',
      ],
      estimatedTime: '40-48+ hours',
    },
    {
      id: '8',
      title: 'API Documentation Generator from Supabase',
      description: 'Automatically generate beautiful, searchable API docs from your Supabase schema with Figma design system integration.',
      score: 84,
      category: 'Developer Tools',
      difficulty: 'intermediate',
      techRequirements: 'moderate',
      sponsors: ['Supabase', 'Algolia', 'Figma'],
      why: 'Solves a common developer pain point. The auto-generation aspect saves time and the design system integration shows attention to presentation. Very practical with clear business value.',
      leverages: [
        'Supabase schema introspection and metadata APIs',
        'Algolia DocSearch for comprehensive API documentation search',
        'Figma components for consistent documentation design',
        'Reduces documentation maintenance burden',
      ],
      requiredSkills: [
        'Understanding of API documentation best practices',
        'Supabase introspection features',
        'Static site generation',
        'Search implementation',
      ],
      estimatedTime: '20-28 hours',
    },
  ];

  // Filter projects to only include those that use at least one of the provided sponsors
  return baseProjects.filter(project => 
    project.sponsors.some(sponsor => sponsors.includes(sponsor))
  );
}
